services:
  - type: web
    name: stock-market-backend
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt

    startCommand: python backend/app.py

    autoDeploy: true

